version: 0.2
# AWS CodeBuild spec.
# See : https://docs.aws.amazon.com/codebuild/latest/userguide/build-spec-ref.html
env:
  variables:
    SLS_DEBUG: "*"
    REGION: "eu-west-1"
    ENVIRONMENT: "test"
    REDIS_PORT: "6378"
    REDIS_URL: "redis://127.0.0.1"
    SECRET_KEY: "04a0cdf1c982459fba12a554f85196a5"
    TABLE_NAME: "GATEKEEPER-USERS-TEST"
phases:
  install:
    commands:
      - nodejs --version
      - npm --version
      - echo "******* serverless.yml ********"
      - cp serverless.yml.dist serverless.yml
      - sed -i -e "s/ENVIRONMENT_PLACEHOLDER/${ENVIRONMENT}/g" serverless.yml
      - sed -i -e "s/SECRET_KEY_PLACEHOLDER/${SECRET_KEY}/g" serverless.yml
      - sed -i -e "s/REGION_PLACEHOLDER/${REGION}/g" serverless.yml
      - sed -i -e "s/REDIS_PORT_PLACEHOLDER/${REDIS_PORT}/g" serverless.yml
      - sed -i -e "s#REDIS_URL_PLACEHOLDER#${REDIS_URL}#g" serverless.yml
      - sed -i -e "s#TABLE_NAME_PLACEHOLDER#${TABLE_NAME}#g" serverless.yml
      - cat serverless.yml
      - echo "***** end serverless.yml ******"
      - docker pull amazon/dynamodb-local
      - docker pull redis
      - npm install
      - npm install -g serverless
  pre_build:
    commands:
      - npm run docker-start
  build:
    commands:
      - npm run test-aws-codebuild
  post_build:
    commands:
      - npm run docker-stop
      - npm run docker-remove-container
      - rm -f serverless.yml
      - mv serverless.yml.dist serverless.yml
      - sed -i -e "s/ENVIRONMENT_PLACEHOLDER/${ENVIRONMENT_PRODUCTION}/g" serverless.yml
      - sed -i -e "s/SECRET_KEY_PLACEHOLDER/${SECRET_KEY_PRODUCTION}/g" serverless.yml
      - sed -i -e "s/REGION_PLACEHOLDER/${REGION_PRODUCTION}/g" serverless.yml
      - sed -i -e "s/REDIS_PORT_PLACEHOLDER/${REDIS_PORT_PRODUCTION}/g" serverless.yml
      - sed -i -e "s#REDIS_URL_PLACEHOLDER#${REDIS_URL_PRODUCTION}#g" serverless.yml
      - sed -i -e "s#TABLE_NAME_PLACEHOLDER#${TABLE_NAME_PRODUCTION}#g" serverless.yml
      - sls deploy
      - exit $?

